proxy:
    work: ENC[AES256_GCM,data:EXPbDTXD7kXzi0nuzUfoG0fc+VDFNtY8hpRpN55nQgfI,iv:UsLwIHwJRbF2BRPEIHsGom2SCI+CERY8EFuECvZc6B0=,tag:3NSgPsRWcK+q4IF1j5FCfA==,type:str]
    clash: ENC[AES256_GCM,data:amOlsXINLHpzHEWqtRIp4XK+I0AIdO4X1CA=,iv:Cjwo9peFh77lkC00zYvakAFnctSUKo0z8IyBxf1+OKY=,tag:/K45G4x+B7UjiZR0/LQwXw==,type:str]
ssh_pub_key: ENC[AES256_GCM,data:JG660/zxGZQaV57FsXyrTaoFENg1XkQnvLn5qEYc4NyxgOrE8yED9zVcglV06pkhmBTJCdadgqQSBr/rPL+k4zQfHSQqNtnQd2JVv88eoEw=,iv:3BmK7gDa0AVC6SVEZqRBB19UYsOB+cODKRsivORlve8=,tag:g3CTZSlg/g7QSeAm1cB2fQ==,type:str]
atuin_key: ENC[AES256_GCM,data:ot7qAVZYJI/yUMY9ViObpvUZb1xqVIK8+C2UXS2K42RYh2dVbW06xBygwOp2hgoY,iv:LjQAXNQbUALlvxuNGcQYmZjiSv1HIsw8v2SRvg7REDc=,tag:o12XMAu9ZYiEsEfqnF1R/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15meyx2lnegjd0rgzzg4k7yv3m45yl9jurfq6p2mssh2vzkkhmdlqsepnvr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjY1U2VUVQeWpETk0yVmJq
            RDVDejd4T0FFckZuQ3pIY1NOU2p1amhPOXlvCjJ4MTVodm03cCtidDlvMG1VZ1NU
            RXB3amFqKzVXOS80ZHRjMkQyY0E2WXMKLS0tIDhXdGR4dkZtSkVVMGhyUDU0eTds
            V1VZK3p5bUhmRTJJelY4K0RiZFBOTGcK0nf4vVLp0pGrwhbveWHKZ+Nn10PWmEYw
            ldJh49AHFS0PVr68vibHBsoXGo/ZHhQ4QheT7qcmsIL2oC0gGcsxyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-08T10:03:18Z"
    mac: ENC[AES256_GCM,data:Ylswos9lmeEB2YCRIiYnYZVa8bSTGJCxzvSgWEz+TKXmNjX1d1+Qqiek2tu5rYDePV2qld+1wLx6waZBxSHD1nAOA0ikWEXa7j5cwEG5B6kpwqd4qBZDoR5FnPL/hn/8JN1c509tMl2P52dAns+S8+bkA0qKyk5TzwpgWNsjhxc=,iv:J6tjeDVfDSyrRtazTI6xxnuDqqJhnoPwazR4p2nP9Gk=,tag:qn0zHAKRQv34PU4mWS0hpg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
