proxy:
    work: ENC[AES256_GCM,data:EXPbDTXD7kXzi0nuzUfoG0fc+VDFNtY8hpRpN55nQgfI,iv:UsLwIHwJRbF2BRPEIHsGom2SCI+CERY8EFuECvZc6B0=,tag:3NSgPsRWcK+q4IF1j5FCfA==,type:str]
    clash: ENC[AES256_GCM,data:irW05mUODpZrMLUoV71wFv1XLaocogQESg==,iv:iU3DRAYCxqFpzAw3JOdWgvH1EWcPRzsWZb9AU07tDpM=,tag:4nnSQMKqvIHI89tbg0+ahg==,type:str]
wg:
    privatekey: ENC[AES256_GCM,data:F5J0muALm7aTQ8FUZash5VUy23QDkz6ueUviwUZGS8V/9aZ98XQ/UM9bSBE=,iv:mfMMWehKjP73Q4qKwamzgMQ0ue6rpDVEq6NmLk2p7bU=,tag:UhOenn1y5AZgVrd/W9IXxA==,type:str]
    pubkey: ENC[AES256_GCM,data:aUzXHroaZhsFsTM+DuzPWeB/uvjL5Ue33+qKICzuykc1G1uDsAh6QmiRVNc=,iv:KE2kZ1iIcWJrT0U2o38UHqeNy5dPJlIYU+HudFf9Dxg=,tag:gT+iw/jKQSmQ7g8/CIQ5nw==,type:str]
    endpoint: ENC[AES256_GCM,data:kOPuu14IMen6TTE4R4nHDHTb5y7ju6I=,iv:RvXUi524mdFb1t6XzddoyoPKvHkZWfe40QuUQR5bUrw=,tag:2uNkKxGdTsTd7blFEagOow==,type:str]
ssh_pub_key: ENC[AES256_GCM,data:gtP2tsn93ZGjTtK/GXzHTZ+HsekBsUfQahwMveMR69ZGdyH1LrvEJyEgv4j2X82Vdq11L6fzS2bO80CDEemFfNMo8f/voqMtQIMvh74NaAbPBMnX6EfPcSnpwsjbJA==,iv:UDEXMnT2pkGzAWIporJ1ttTKrqMoy8yz5nCTZs8Xh14=,tag:pzuM/7+4LosTK8gcZu0vbQ==,type:str]
#ENC[AES256_GCM,data:wEFVMuhBFINgyb2LOBK/,iv:7j89Tn2mlyXUeusgxLmn3KsUJc6KRGpsxEwFCKmlMsI=,tag:cxIr1ihyex74WKB246EIxA==,type:comment]
#ENC[AES256_GCM,data:ZvvK3oQfEh0PidqV5WfiLcV4ul/d,iv:zHGscvLKkwkpxH3Q+veBOAhNKu6tjxRpxTZoEBl/ock=,tag:KZElICQWk82W+4VYd7jY1w==,type:comment]
#ENC[AES256_GCM,data:i14KvPgXa0Z9G6wtfKaH6M06Yks2fcJzAN9a,iv:ItfVv845M4m4Kz6lavJnACrlbzCUlfdAFIIV7I5sw+o=,tag:gKBpcexm1ODBGJ07x9+thA==,type:comment]
#ENC[AES256_GCM,data:5nPmsNDNRYiwetir0aHYtb3j,iv:0BqZFBvrDcDATtTYwBshsgc0nF6ExpettIzyzI9gfNo=,tag:aUbDIZD/DExSy15QDOGaSQ==,type:comment]
#ENC[AES256_GCM,data:xGQVDUh8ibN802M=,iv:yTpVt2503X0XXy1m47geOJgRoNm6ROtn/c6v2MMCNKI=,tag:r2SmjU4qrevFLgsoG5+N1A==,type:comment]
#ENC[AES256_GCM,data:LZDJU5XTSRFvgEyH,iv:3Q9cQDCXqFR7WT+yIk90d0xnCD3/OYarasp6FjXLfKg=,tag:2H7TGFUhJxgf2Mb0xPbwqw==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15meyx2lnegjd0rgzzg4k7yv3m45yl9jurfq6p2mssh2vzkkhmdlqsepnvr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjY1U2VUVQeWpETk0yVmJq
            RDVDejd4T0FFckZuQ3pIY1NOU2p1amhPOXlvCjJ4MTVodm03cCtidDlvMG1VZ1NU
            RXB3amFqKzVXOS80ZHRjMkQyY0E2WXMKLS0tIDhXdGR4dkZtSkVVMGhyUDU0eTds
            V1VZK3p5bUhmRTJJelY4K0RiZFBOTGcK0nf4vVLp0pGrwhbveWHKZ+Nn10PWmEYw
            ldJh49AHFS0PVr68vibHBsoXGo/ZHhQ4QheT7qcmsIL2oC0gGcsxyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-05T10:50:34Z"
    mac: ENC[AES256_GCM,data:w91HwtoLkcaOSjD/2kVCJew2mxNa0hnl3m15aev8n02zigrajU4HAXrHofmChZMng5C+i+SFpFZ/6hhUoyMPUEXAsNcUQbMRi/HLMVjJ82XTeAb8k/fMgk2Q59NI1fS1QXMs3qTYUGfq6B8eyGLPk+idNBgy3ls0rZpX6iopexY=,iv:qEChnQpCi9oouJwsZFNlcTk3Pc7joPwTXWf9v48LVY4=,tag:Aw2aE0wePI/hkHO0QTBVrw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
