proxy:
    work: ENC[AES256_GCM,data:EXPbDTXD7kXzi0nuzUfoG0fc+VDFNtY8hpRpN55nQgfI,iv:UsLwIHwJRbF2BRPEIHsGom2SCI+CERY8EFuECvZc6B0=,tag:3NSgPsRWcK+q4IF1j5FCfA==,type:str]
    clash: ENC[AES256_GCM,data:amOlsXINLHpzHEWqtRIp4XK+I0AIdO4X1CA=,iv:Cjwo9peFh77lkC00zYvakAFnctSUKo0z8IyBxf1+OKY=,tag:/K45G4x+B7UjiZR0/LQwXw==,type:str]
wg:
    privatekey: ENC[AES256_GCM,data:F5J0muALm7aTQ8FUZash5VUy23QDkz6ueUviwUZGS8V/9aZ98XQ/UM9bSBE=,iv:mfMMWehKjP73Q4qKwamzgMQ0ue6rpDVEq6NmLk2p7bU=,tag:UhOenn1y5AZgVrd/W9IXxA==,type:str]
    pubkey: ENC[AES256_GCM,data:aUzXHroaZhsFsTM+DuzPWeB/uvjL5Ue33+qKICzuykc1G1uDsAh6QmiRVNc=,iv:KE2kZ1iIcWJrT0U2o38UHqeNy5dPJlIYU+HudFf9Dxg=,tag:gT+iw/jKQSmQ7g8/CIQ5nw==,type:str]
    endpoint: ENC[AES256_GCM,data:kOPuu14IMen6TTE4R4nHDHTb5y7ju6I=,iv:RvXUi524mdFb1t6XzddoyoPKvHkZWfe40QuUQR5bUrw=,tag:2uNkKxGdTsTd7blFEagOow==,type:str]
ssh_pub_key: ENC[AES256_GCM,data:gtP2tsn93ZGjTtK/GXzHTZ+HsekBsUfQahwMveMR69ZGdyH1LrvEJyEgv4j2X82Vdq11L6fzS2bO80CDEemFfNMo8f/voqMtQIMvh74NaAbPBMnX6EfPcSnpwsjbJA==,iv:UDEXMnT2pkGzAWIporJ1ttTKrqMoy8yz5nCTZs8Xh14=,tag:pzuM/7+4LosTK8gcZu0vbQ==,type:str]
atuin_key: ENC[AES256_GCM,data:ot7qAVZYJI/yUMY9ViObpvUZb1xqVIK8+C2UXS2K42RYh2dVbW06xBygwOp2hgoY,iv:LjQAXNQbUALlvxuNGcQYmZjiSv1HIsw8v2SRvg7REDc=,tag:o12XMAu9ZYiEsEfqnF1R/A==,type:str]
#ENC[AES256_GCM,data:wEFVMuhBFINgyb2LOBK/,iv:7j89Tn2mlyXUeusgxLmn3KsUJc6KRGpsxEwFCKmlMsI=,tag:cxIr1ihyex74WKB246EIxA==,type:comment]
#ENC[AES256_GCM,data:ZvvK3oQfEh0PidqV5WfiLcV4ul/d,iv:zHGscvLKkwkpxH3Q+veBOAhNKu6tjxRpxTZoEBl/ock=,tag:KZElICQWk82W+4VYd7jY1w==,type:comment]
#ENC[AES256_GCM,data:i14KvPgXa0Z9G6wtfKaH6M06Yks2fcJzAN9a,iv:ItfVv845M4m4Kz6lavJnACrlbzCUlfdAFIIV7I5sw+o=,tag:gKBpcexm1ODBGJ07x9+thA==,type:comment]
#ENC[AES256_GCM,data:5nPmsNDNRYiwetir0aHYtb3j,iv:0BqZFBvrDcDATtTYwBshsgc0nF6ExpettIzyzI9gfNo=,tag:aUbDIZD/DExSy15QDOGaSQ==,type:comment]
#ENC[AES256_GCM,data:xGQVDUh8ibN802M=,iv:yTpVt2503X0XXy1m47geOJgRoNm6ROtn/c6v2MMCNKI=,tag:r2SmjU4qrevFLgsoG5+N1A==,type:comment]
#ENC[AES256_GCM,data:LZDJU5XTSRFvgEyH,iv:3Q9cQDCXqFR7WT+yIk90d0xnCD3/OYarasp6FjXLfKg=,tag:2H7TGFUhJxgf2Mb0xPbwqw==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15meyx2lnegjd0rgzzg4k7yv3m45yl9jurfq6p2mssh2vzkkhmdlqsepnvr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjY1U2VUVQeWpETk0yVmJq
            RDVDejd4T0FFckZuQ3pIY1NOU2p1amhPOXlvCjJ4MTVodm03cCtidDlvMG1VZ1NU
            RXB3amFqKzVXOS80ZHRjMkQyY0E2WXMKLS0tIDhXdGR4dkZtSkVVMGhyUDU0eTds
            V1VZK3p5bUhmRTJJelY4K0RiZFBOTGcK0nf4vVLp0pGrwhbveWHKZ+Nn10PWmEYw
            ldJh49AHFS0PVr68vibHBsoXGo/ZHhQ4QheT7qcmsIL2oC0gGcsxyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-13T13:11:14Z"
    mac: ENC[AES256_GCM,data:rRFld0xcODKXA+UcIXK9Szf9sqyKXkyH/qsOw8695kKpi0ZyzTCmb6xFZFRPpeReQh1cYia0AU/UT1Op+TmIXk0Nw7s5LTRG+ZKAz4V7eH7HLTpw0+cB2bSvbEC7cHOMIuPtAcZFpExFePb6z1GZnlbREBmu5mBChPHOaxhjIzk=,iv:7dXkmmz0sCC4bvb9QQDVy3/Tz4HUfYNEaCE7Se1VDbA=,tag:SrR7R25DVXH+WRkP9oNP6g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
